# this project is no longer use, use goweb instead of
application: fbbcfaab60da26f9b38f38fa658910
version: 1
runtime: go
api_version: go1


handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /s
  static_dir: static
- url: /.*
  script: _go_app
